- name: copy template zabbix_server.conf
  template:
    dest: /etc/zabbix
    src: zabbix_server.conf

- name: Start service zabbix-server
  service:
      name: zabbix-server
      enabled: yes
      state: restarted
...