---
- name: Check that the create.sql.gz exists
  stat:
    path: /usr/share/doc/zabbix-sql-scripts/mysql/server.sql.gz
  register: create_sql_gz_exist

- name: Unarchive create.sql.gz
  command: gunzip /usr/share/doc/zabbix-sql-scripts/mysql/server.sql.gz
  when: create_sql_gz_exist.stat.exists
  
- name: Create database
  mysql_db:
    login_host: localhost
    login_password: "{{ login_mysql_password }}"
    login_user: "{{ login_mysql_user }}"
    name: "{{ DBName }}"
    encoding: utf8
    collation: utf8_bin  
  register: db_created    

- mysql_user:
    login_host: localhost
    login_password: "{{ login_mysql_password }}"
    login_user: "{{ login_mysql_user }}"
    name: "{{ DBUser }}"
    password: "{{ DBPassword }}"
    priv: '*.*:ALL'
    state: present
    host: "{{ item }}"
  with_items:
    - "{{ zabbix_server_address }}"
    - "{{ zabbix_frontend_address }}"
    - "{{ DBHost_address }}"
    - "{{ zabbix_node2_address }}"

- name: Import schema and data
  mysql_db:
    state: import
    login_host: "{{ DBHost_address }}"
    login_password: "{{ DBPassword }}"
    login_user: "{{ DBUser }}"
    name: "{{ DBName }}"
    encoding: utf8
    collation: utf8_bin
    target: /usr/share/doc/zabbix-sql-scripts/mysql/server.sql
  when: db_created.changed  
 
- name: copy template zabbix_server.conf
  template:
    dest: /etc/zabbix
    src: zabbix_server.conf

- name: Start service httpd
  service:
      name: httpd
      enabled: yes
      state: restarted

- name: Start service php-fpm
  service:
      name: php-fpm
      enabled: yes
      state: restarted 

- name: Start service zabbix-server
  service:
      name: zabbix-server
      enabled: yes
      state: restarted
...